### PR TITLE
Add logic for parsing the s3_path properly

### PR DESCRIPTION
**Pull request by nunopato**
- A `s3_bucket` might simply be something like `s3_bucket_name` or it might contain subdirectories as in `s3_bucket_name/my_subdir`. Mothership is now doing some trickery to parse that string and call `aws s3 cp` and `aws deployment create` with the right arguments.

- The work in the following PR, https://github.com/codeship/mothership/pull/6079, changes the AWS deployment models to directly call the scripts within this repo (`aws-utilities`). Since mothership will now pass the entire string (with subdirs) we need to update the scripts to accommodate that. 

- The current scripts do not support subdirs.

### CODE REVIEW

**Comment by LarsFronius** [comment]
That's awesome! :shipit: 

Shall we possibly update the UI for deployments slightly to claim that we actually support subfolders in buckets, e.g. here https://github.com/codeship/mothership/blob/aab324130fda7700dbdb529f6a0704f74392355d/app/views/s3_deployments/_s3_deployment.html.slim#L17
Given the effort you put into making this solid, I reckon we should also make an effort communicating it better? :)

**Comment by nunopato** [comment]
@LarsFronius what's the weird case you are thinking about? I think we're also doing some validation on mothership.

**Comment by LarsFronius** [comment]
@nunopato I am thinking about just changing https://github.com/codeship-library/aws-utilities/blob/master/deployment/test/elastic_beanstalk/integration-test#L27 and https://github.com/codeship-library/aws-utilities/blob/master/deployment/test/code_deploy/integration-test#L40 up to use an s3 bucket with a subdirectory, to trigger your codepaths for splitting the s3_bucket into the bucket name and the subdirectory in the integration tests.

**Comment by nunopato** [comment]
@LarsFronius I did that but changed the code back to the current S3. The problem with having both is that the build time increases a lot. We cannot have multiple CodeDeploy deployments in parallel.

**Pull request merged**
